export const RECEIVED_LEAGUES = 'RECEIVED_LEAGUES';
export const RECEIVED_SPORTS = 'RECEIVED_SPORTS';
export const REQUESTED_LEAGUES = 'REQUESTED_LEAGUES';
export const REQUESTED_NEW_LEAGUE = 'REQUESTED_NEW_LEAGUE';
export const RECEIVED_NEW_LEAGUE = 'RECEIVED_NEW_LEAGUE';
