export const HIDE_NEW_LEAGUE_MODAL = 'HIDE_NEW_LEAGUE_MODAL';
export const RECEIVED_LEAGUES = 'RECEIVED_LEAGUES';
export const RECEIVED_NEW_LEAGUE = 'RECEIVED_NEW_LEAGUE';
export const RECEIVED_SPORTS = 'RECEIVED_SPORTS';
export const SHOW_NEW_LEAGUE_MODAL = 'SHOW_NEW_LEAGUE_MODAL';
